listener 1883
allow_anonymous false
password_file /mosquitto/secrets/passwd
acl_file /mosquitto/secrets/acl

listener 9001
protocol websockets
allow_anonymous false
password_file /mosquitto/secrets/passwd
acl_file /mosquitto/secrets/acl
